//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraProductos
    {
        public int CompraId { get; set; }
        public int Proveedor { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int Producto { get; set; }
        public int CantidadProductoComprado { get; set; }
        public decimal PrecioProductoComprado { get; set; }
        public int Admin { get; set; }
    
        public virtual Admin Admin1 { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
