//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int DetalleFacturaId { get; set; }
        public int Venta { get; set; }
        public int ProductoVendido { get; set; }
        public int CantidadVendido { get; set; }
        public decimal ValorProductoVendido { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
