//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int DevolucionId { get; set; }
        public int VentaAsociada { get; set; }
        public int ProductoDevuelto { get; set; }
        public int CantidadprodDevuelto { get; set; }
        public string MotivoDevolucion { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public int VendedorAtendio { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
