//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public HistoriaClinica()
        {
            this.Receta = new HashSet<Receta>();
        }
    
        public int HistoriaClinicaId { get; set; }
        public System.DateTime FechaHistoria { get; set; }
        public string MotivoHistoria { get; set; }
        public string ObservacionHistoria { get; set; }
        public string MedicamentoHistoria { get; set; }
        public int Mascota { get; set; }
        public int Veterinario { get; set; }
    
        public virtual Mascota Mascota1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
