//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CompraProductos = new HashSet<CompraProductos>();
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public int ProductoId { get; set; }
        public string CodigoProducto { get; set; }
        public string NombreProducto { get; set; }
        public int CantidadProducto { get; set; }
        public decimal precioProducto { get; set; }
        public int SedePertenece { get; set; }
        public int ProveedorSurte { get; set; }
    
        public virtual ICollection<CompraProductos> CompraProductos { get; set; }
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
