//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Producto = new HashSet<Producto>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int SedeId { get; set; }
        public string NombreSede { get; set; }
        public string DireccionSede { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
