//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebajasDelCampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.CompraProductos = new HashSet<CompraProductos>();
            this.CompraProductos1 = new HashSet<CompraProductos>();
            this.Devolucion = new HashSet<Devolucion>();
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
            this.Mascota = new HashSet<Mascota>();
            this.Producto = new HashSet<Producto>();
            this.Venta = new HashSet<Venta>();
            this.Venta1 = new HashSet<Venta>();
        }
    
        public int UsuarioId { get; set; }
        public string CedulaUser { get; set; }
        public string NombresUser { get; set; }
        public string ApellidosUser { get; set; }
        public string TelefonoUser { get; set; }
        public string DireccionUser { get; set; }
        public int TipoUser { get; set; }
        public string Sexouser { get; set; }
        public string CorreoUser { get; set; }
        public string EstadoUser { get; set; }
        public string User { get; set; }
        public byte[] Pass { get; set; }
        public int Sede { get; set; }
    
        public virtual ICollection<CompraProductos> CompraProductos { get; set; }
        public virtual ICollection<CompraProductos> CompraProductos1 { get; set; }
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
        public virtual ICollection<Mascota> Mascota { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual Sede Sede1 { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual ICollection<Venta> Venta1 { get; set; }
    }
}
